# Dockerfile.flask
FROM python:3.14-slim

WORKDIR /app

# Copier le fichier requirements et installer les dépendances
COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier tout le code de l'application
COPY . .

# Exposer le port 8000
EXPOSE 8000

# Lancer l'application Flask
CMD ["python", "app/app.py"]
